spring:
  profiles:
    # demo: 演示环境，内置数据库；pro 生产环境，mysql数据库
    active: ${active:dev}
  # hibernate 数据库 验证级别
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${show-sql:false}
    # 在同一请求中使用同一个EntityManager
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
  #    open-in-view: false
  # 启用 flyway
  flyway:
    enabled: false

  # 上传文件大小限制
  servlet:
    multipart:
      enabled: true
      max-file-size: ${file.size:20MB}
      max-request-size: ${file.size:20MB}

server:
  # 配置端口
  port: ${port:8003}
  servlet:
    session:
      timeout: 60m


app:
  # 短消息类型
  sms-type: ${sms-type:local}
  # 初始化管理员用户名
  username: ${default-username:13920618851}
  # 初始化管理员密码
  password: ${default-password:admin}
  #  短信平台
  sms:
    access-key-id: 8TkA3lc5Vo8ub2Cj
    access-secret: 3Q7OleKWhQuDlWPJ3rrXCkO3iYKAzj
    sign-name: 金耕科技
  monitor:
    enable: false
    url: http://localhost:8001/api/log/batchSave?token=zYEq7Js5bNOtWWYuVc8yCfS3fYnuheeo
---
spring:
  config:
    activate:
      on-profile: pro
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  # 配置数据源
  datasource:
    url: jdbc:mysql://${datasource.url:127.0.0.1}:${datasource.port:3306}/${datasource.dbname:magnetic}?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${datasource.username:root}
    password: ${datasource.password:}

---
# PJ专用数据库
spring:
  config:
    activate:
      on-profile: dev-pj
  flyway:
    enabled: false
  datasource:
    url: jdbc:mysql://${datasource.url:10.112.205.113}:${datasource.port:3306}/${datasource.dbname:magnetic}?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${datasource.username:root}
    password: ${datasource.password:Bupt@2023}

---
# docker专用数据库
spring:
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: false
  datasource:
    url: jdbc:mysql://${datasource.url:10.112.205.113}:${datasource.port:3307}/${datasource.dbname:magnetic}?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: ${datasource.username:root}
    password: ${datasource.password:Bupt@2023}
---
spring:
  config:
    activate:
      on-profile: demo
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
  # H2数据源,请在当前用户所有文件夹下建立data文件夹，并保证其可写
  # 或者自行指定其它文件位置
  datasource:
    url: jdbc:h2:~/data/db
